export const lookupTypes = [
  { code: "record_status", name: "Record status", is_status: true, is_system: true },
  { code: "approval_status", name: "Approval status", is_status: true, is_system: true },
  { code: "rule_status", name: "Rule status", is_status: true, is_system: true },
  { code: "session_status", name: "Academic session status", is_status: true, is_system: true },
  { code: "user_status", name: "User account status", is_status: true, is_system: true },
  { code: "notification_status", name: "Notification status", is_status: true, is_system: true },
  { code: "gender", name: "Gender", is_status: false, is_system: true },
  { code: "religion", name: "Religion", is_status: false, is_system: true },
  { code: "blood_group", name: "Blood group", is_status: false, is_system: true },
  { code: "nationality", name: "Nationality", is_status: false, is_system: true },
  { code: "relationship_type", name: "Relationship type", is_status: false, is_system: true },
  { code: "employee_group", name: "Employee group", is_status: false, is_system: true },
  { code: "profile_type", name: "Profile type", is_status: false, is_system: true },
  { code: "contact_kind", name: "Contact kind", is_status: false, is_system: true },
  { code: "address_kind", name: "Address kind", is_status: false, is_system: true },
  { code: "identifier_type", name: "Identifier type", is_status: false, is_system: true },
  { code: "geo_level", name: "Geographic level", is_status: false, is_system: true },
  { code: "scope_type", name: "Scope type", is_status: false, is_system: true },
  { code: "data_type", name: "Data type", is_status: false, is_system: true },
  { code: "permission_action", name: "Permission action", is_status: false, is_system: true },
  { code: "approver_type", name: "Approver type", is_status: false, is_system: true },
  { code: "approval_action_type", name: "Approval action", is_status: false, is_system: true },
  { code: "template_type", name: "Template type", is_status: false, is_system: true },
  { code: "notification_channel", name: "Notification channel", is_status: false, is_system: true },
  { code: "device_platform", name: "Device platform", is_status: false, is_system: true },
  { code: "custom_entity_type", name: "Custom-field entity", is_status: false, is_system: true },
  { code: "department_type", name: "Department type", is_status: false, is_system: true },
  { code: "rule_eval_mode", name: "Rule evaluation mode", is_status: false, is_system: true },
  { code: "student_status", name: "Student status", is_status: true, is_system: true },
  { code: "enrollment_status", name: "Enrollment status", is_status: true, is_system: true },
  { code: "incident_category", name: "Incident category", is_status: false, is_system: true },
  { code: "incident_severity", name: "Incident severity", is_status: false, is_system: true },
  { code: "exit_type", name: "Student exit type", is_status: false, is_system: true },
  { code: "exit_status", name: "Exit / TC status", is_status: true, is_system: true },
  { code: "application_status", name: "Admission application status", is_status: true, is_system: true },
  { code: "form_sale_status", name: "Admission form sale status", is_status: true, is_system: true },
  { code: "enquiry_status", name: "Enquiry status", is_status: true, is_system: true },
  { code: "enquiry_source", name: "Enquiry source", is_status: false, is_system: true },
  { code: "visitor_purpose", name: "Visitor purpose", is_status: false, is_system: true },
  { code: "call_direction", name: "Call direction", is_status: false, is_system: true },
  { code: "postal_direction", name: "Postal direction", is_status: false, is_system: true },
  { code: "complaint_status", name: "Complaint status", is_status: true, is_system: true },
  { code: "complaint_source", name: "Complaint source", is_status: false, is_system: true },
  { code: "pass_type", name: "Gate / temporary pass type", is_status: false, is_system: true },
  { code: "pass_status", name: "Pass status", is_status: true, is_system: true },
  { code: "holiday_type", name: "Holiday type", is_status: false, is_system: true },
  { code: "event_audience", name: "Event audience", is_status: false, is_system: true },
  { code: "notice_audience", name: "Notice audience", is_status: false, is_system: true },
];

export const lookupValues = [
  ["record_status", "active", "Active", 1, false],
  ["record_status", "inactive", "Inactive", 2, false],
  ["record_status", "archived", "Archived", 3, true],
  ["approval_status", "pending", "Pending", 1, false],
  ["approval_status", "on_hold", "On hold", 2, false],
  ["approval_status", "approved", "Approved", 3, true],
  ["approval_status", "rejected", "Rejected", 4, true],
  ["approval_status", "cancelled", "Cancelled", 5, true],
  ["rule_status", "draft", "Draft", 1, false],
  ["rule_status", "published", "Published", 2, false],
  ["rule_status", "archived", "Archived", 3, true],
  ["session_status", "planned", "Planned", 1, false],
  ["session_status", "open", "Open", 2, false],
  ["session_status", "closed", "Closed", 3, true],
  ["user_status", "pending", "Pending activation", 1, false],
  ["user_status", "active", "Active", 2, false],
  ["user_status", "suspended", "Suspended", 3, false],
  ["user_status", "disabled", "Disabled", 4, true],
  ["notification_status", "queued", "Queued", 1, false],
  ["notification_status", "sent", "Sent", 2, false],
  ["notification_status", "failed", "Failed", 3, true],
  ["notification_status", "read", "Read", 4, true],
  ["gender", "male", "Male", 1, false],
  ["gender", "female", "Female", 2, false],
  ["religion", "islam", "Islam", 1, false],
  ["religion", "christianity", "Christianity", 2, false],
  ["religion", "hinduism", "Hinduism", 3, false],
  ["religion", "buddhism", "Buddhism", 4, false],
  ["religion", "other", "Other", 9, false],
  ["blood_group", "a_pos", "A+", 1, false],
  ["blood_group", "a_neg", "A-", 2, false],
  ["blood_group", "b_pos", "B+", 3, false],
  ["blood_group", "b_neg", "B-", 4, false],
  ["blood_group", "ab_pos", "AB+", 5, false],
  ["blood_group", "ab_neg", "AB-", 6, false],
  ["blood_group", "o_pos", "O+", 7, false],
  ["blood_group", "o_neg", "O-", 8, false],
  ["nationality", "bangladeshi", "Bangladeshi", 1, false],
  ["relationship_type", "father", "Father", 1, false],
  ["relationship_type", "mother", "Mother", 2, false],
  ["relationship_type", "guardian", "Guardian", 3, false],
  ["relationship_type", "brother", "Brother", 4, false],
  ["relationship_type", "sister", "Sister", 5, false],
  ["relationship_type", "grandparent", "Grandparent", 6, false],
  ["relationship_type", "uncle", "Uncle", 7, false],
  ["relationship_type", "aunt", "Aunt", 8, false],
  ["relationship_type", "other", "Other", 9, false],
  ["employee_group", "teaching", "Teaching staff", 1, false],
  ["employee_group", "administrative", "Administrative staff", 2, false],
  ["employee_group", "support", "Support staff", 3, false],
  ["contact_kind", "phone", "Phone", 1, false],
  ["contact_kind", "whatsapp", "WhatsApp", 2, false],
  ["contact_kind", "email", "Email", 3, false],
  ["address_kind", "present", "Present address", 1, false],
  ["address_kind", "permanent", "Permanent address", 2, false],
  ["identifier_type", "national_id", "National ID", 1, false],
  ["identifier_type", "birth_certificate", "Birth certificate", 2, false],
  ["identifier_type", "passport", "Passport", 3, false],
  ["identifier_type", "tin", "TIN", 4, false],
  ["geo_level", "country", "Country", 1, false],
  ["geo_level", "division", "Division", 2, false],
  ["geo_level", "district", "District", 3, false],
  ["geo_level", "upazila", "Upazila / Thana", 4, false],
  ["department_type", "academic", "Academic", 1, false],
  ["department_type", "administrative", "Administrative", 2, false],
  ["profile_type", "staff", "Staff", 1, false],
  ["profile_type", "student", "Student", 2, false],
  ["profile_type", "parent", "Parent", 3, false],
  ["scope_type", "global", "Global", 1, false],
  ["scope_type", "campus", "Campus", 2, false],
  ["scope_type", "employee_group", "Employee group", 3, false],
  ["scope_type", "department", "Department", 4, false],
  ["scope_type", "designation", "Designation", 5, false],
  ["scope_type", "class_level", "Class level", 6, false],
  ["data_type", "text", "Text", 1, false],
  ["data_type", "number", "Number", 2, false],
  ["data_type", "date", "Date", 3, false],
  ["data_type", "boolean", "Yes / No", 4, false],
  ["data_type", "select", "Single choice", 5, false],
  ["data_type", "multi_select", "Multiple choice", 6, false],
  ["data_type", "json", "JSON", 7, false],
  ["permission_action", "view", "View", 1, false],
  ["permission_action", "create", "Create", 2, false],
  ["permission_action", "update", "Update", 3, false],
  ["permission_action", "delete", "Delete", 4, false],
  ["permission_action", "approve", "Approve", 5, false],
  ["permission_action", "export", "Export", 6, false],
  ["permission_action", "print", "Print", 7, false],
  ["approver_type", "role", "Role", 1, false],
  ["approver_type", "designation", "Designation", 2, false],
  ["approver_type", "user", "Specific user", 3, false],
  ["approval_action_type", "approve", "Approve", 1, false],
  ["approval_action_type", "reject", "Reject", 2, false],
  ["approval_action_type", "return", "Return for changes", 3, false],
  ["approval_action_type", "comment", "Comment", 4, false],
  ["template_type", "letter", "Letter", 1, false],
  ["template_type", "certificate", "Certificate", 2, false],
  ["template_type", "sms", "SMS", 3, false],
  ["template_type", "email", "Email", 4, false],
  ["template_type", "id_card", "ID card", 5, false],
  ["template_type", "report_card", "Report card", 6, false],
  ["notification_channel", "in_app", "In-app", 1, false],
  ["notification_channel", "push", "Push", 2, false],
  ["notification_channel", "sms", "SMS", 3, false],
  ["notification_channel", "email", "Email", 4, false],
  ["device_platform", "android", "Android", 1, false],
  ["device_platform", "ios", "iOS", 2, false],
  ["device_platform", "web", "Web", 3, false],
  ["custom_entity_type", "student", "Student", 1, false],
  ["custom_entity_type", "guardian", "Guardian", 2, false],
  ["custom_entity_type", "employee", "Employee", 3, false],
  ["custom_entity_type", "admission_application", "Admission application", 4, false],
  ["rule_eval_mode", "all_matching", "Apply all matching rules", 1, false],
  ["rule_eval_mode", "first_match", "Apply first matching rule only", 2, false],
  ["student_status", "active", "Active", 1, false],
  ["student_status", "inactive", "Inactive", 2, false],
  ["student_status", "alumni", "Alumni", 3, true],
  ["student_status", "transferred", "Transferred", 4, true],
  ["student_status", "withdrawn", "Withdrawn", 5, true],
  ["enrollment_status", "enrolled", "Enrolled", 1, false],
  ["enrollment_status", "promoted", "Promoted", 2, true],
  ["enrollment_status", "repeated", "Repeated", 3, false],
  ["enrollment_status", "transferred", "Transferred", 4, true],
  ["enrollment_status", "withdrawn", "Withdrawn", 5, true],
  ["incident_category", "discipline", "Discipline", 1, false],
  ["incident_category", "academic", "Academic", 2, false],
  ["incident_category", "health", "Health", 3, false],
  ["incident_category", "other", "Other", 9, false],
  ["incident_severity", "low", "Low", 1, false],
  ["incident_severity", "medium", "Medium", 2, false],
  ["incident_severity", "high", "High", 3, false],
  ["exit_type", "tc", "Transfer certificate", 1, false],
  ["exit_type", "transfer", "Internal transfer", 2, false],
  ["exit_type", "withdrawal", "Withdrawal", 3, false],
  ["exit_status", "draft", "Draft", 1, false],
  ["exit_status", "pending", "Pending approval", 2, false],
  ["exit_status", "issued", "Issued", 3, true],
  ["exit_status", "cancelled", "Cancelled", 4, true],
  ["application_status", "draft", "Draft", 1, false],
  ["application_status", "submitted", "Submitted", 2, false],
  ["application_status", "under_review", "Under review", 3, false],
  ["application_status", "test_scheduled", "Test scheduled", 4, false],
  ["application_status", "waitlisted", "Waitlisted", 5, false],
  ["application_status", "offered", "Offer issued", 6, false],
  ["application_status", "accepted", "Accepted", 7, false],
  ["application_status", "enrolled", "Enrolled", 8, true],
  ["application_status", "rejected", "Rejected", 9, true],
  ["application_status", "withdrawn", "Withdrawn", 10, true],
  ["form_sale_status", "sold", "Sold", 1, false],
  ["form_sale_status", "used", "Used", 2, true],
  ["form_sale_status", "cancelled", "Cancelled", 3, true],
  ["enquiry_status", "open", "Open", 1, false],
  ["enquiry_status", "follow_up", "Follow up", 2, false],
  ["enquiry_status", "converted", "Converted to application", 3, true],
  ["enquiry_status", "closed", "Closed", 4, true],
  ["enquiry_source", "walk_in", "Walk-in", 1, false],
  ["enquiry_source", "phone", "Phone", 2, false],
  ["enquiry_source", "web", "Website", 3, false],
  ["enquiry_source", "referral", "Referral", 4, false],
  ["visitor_purpose", "meeting", "Meeting", 1, false],
  ["visitor_purpose", "admission", "Admission", 2, false],
  ["visitor_purpose", "delivery", "Delivery", 3, false],
  ["visitor_purpose", "other", "Other", 9, false],
  ["call_direction", "inbound", "Inbound", 1, false],
  ["call_direction", "outbound", "Outbound", 2, false],
  ["postal_direction", "in", "Incoming", 1, false],
  ["postal_direction", "out", "Outgoing", 2, false],
  ["complaint_status", "open", "Open", 1, false],
  ["complaint_status", "in_progress", "In progress", 2, false],
  ["complaint_status", "resolved", "Resolved", 3, true],
  ["complaint_status", "closed", "Closed", 4, true],
  ["complaint_source", "parent", "Parent", 1, false],
  ["complaint_source", "student", "Student", 2, false],
  ["complaint_source", "staff", "Staff", 3, false],
  ["pass_type", "gate", "Gate pass", 1, false],
  ["pass_type", "temporary", "Temporary campus pass", 2, false],
  ["pass_status", "active", "Active", 1, false],
  ["pass_status", "used", "Used", 2, true],
  ["pass_status", "expired", "Expired", 3, true],
  ["pass_status", "cancelled", "Cancelled", 4, true],
  ["holiday_type", "public", "Public holiday", 1, false],
  ["holiday_type", "school", "School holiday", 2, false],
  ["holiday_type", "exam_break", "Exam break", 3, false],
  ["event_audience", "all", "Everyone", 1, false],
  ["event_audience", "staff", "Staff", 2, false],
  ["event_audience", "students", "Students", 3, false],
  ["event_audience", "parents", "Parents", 4, false],
  ["notice_audience", "all", "Everyone", 1, false],
  ["notice_audience", "staff", "Staff", 2, false],
  ["notice_audience", "students", "Students", 3, false],
  ["notice_audience", "parents", "Parents", 4, false],
];

export const modules = [
  ["platform_setup", "Platform Setup", 1],
  ["identity_access", "Identity & Access", 2],
  ["shared_services", "Shared Services", 3],
  ["front_office", "Front Office", 4],
  ["admission", "Admission", 5],
  ["student", "Student Management", 6],
  ["academic", "Academic", 7],
  ["academic_calendar", "Academic Calendar & Events", 8],
  ["attendance", "Attendance", 9],
  ["attendance_device", "Attendance Devices", 10],
  ["examination", "Examination & Result", 11],
  ["hifz", "Hifz", 12],
  ["fees", "Fees", 13],
  ["payments", "Payments", 14],
  ["accounts", "Accounts", 15],
  ["inventory", "Inventory & Procurement", 16],
  ["library", "Library", 17],
  ["hr", "HR Core", 18],
  ["roster", "Roster & Duty", 19],
  ["leave", "Leave Management", 20],
  ["payroll", "Payroll & Salary Generator", 21],
  ["transport", "Transport", 22],
  ["communication", "Communication", 23],
  ["student_portal", "Student Portal", 24],
  ["parent_portal", "Parent Portal", 25],
  ["reports", "Reports & Dashboards", 26],
];

export const ruleActionTypes = [
  {
    code: "deduct_days",
    name: "Deduct days of salary",
    description: "Deduct N days of per-day salary",
    params_schema: {
      type: "object",
      properties: {
        days: { type: "number" },
        every: { type: "number", description: "apply once per N occurrences" },
      },
      required: ["days"],
    },
  },
  {
    code: "deduct_amount",
    name: "Deduct fixed amount",
    description: "Deduct a fixed amount",
    params_schema: { type: "object", properties: { amount: { type: "number" } }, required: ["amount"] },
  },
  {
    code: "add_allowance",
    name: "Add allowance / bonus",
    description: "Add an amount or percentage of basic",
    params_schema: {
      type: "object",
      properties: { amount: { type: "number" }, percent_of: { type: "string" } },
    },
  },
  {
    code: "apply_discount",
    name: "Apply discount",
    description: "Discount by amount or percent",
    params_schema: {
      type: "object",
      properties: { amount: { type: "number" }, percent: { type: "number" } },
    },
  },
  {
    code: "set_value",
    name: "Set a computed value",
    description: "Write a value to a named output",
    params_schema: {
      type: "object",
      properties: { target: { type: "string" }, value: {} },
      required: ["target", "value"],
    },
  },
  {
    code: "require_approval",
    name: "Require approval",
    description: "Route through a workflow",
    params_schema: {
      type: "object",
      properties: { workflow_code: { type: "string" } },
      required: ["workflow_code"],
    },
  },
  {
    code: "block",
    name: "Block the action",
    description: "Reject with a message",
    params_schema: {
      type: "object",
      properties: { message: { type: "string" } },
      required: ["message"],
    },
  },
  {
    code: "notify",
    name: "Send notification",
    description: "Queue a notification from a template",
    params_schema: {
      type: "object",
      properties: { template_code: { type: "string" }, channel: { type: "string" } },
      required: ["template_code"],
    },
  },
];

export const entityKeys = [
  "lookup_type",
  "lookup_value",
  "module",
  "campus",
  "school_wing",
  "academic_session",
  "class_level",
  "class_offering",
  "class_section",
  "subject",
  "class_offering_subject",
  "house",
  "department",
  "designation",
  "geo_unit",
  "id_sequence",
  "person",
  "person_contact",
  "person_address",
  "person_identifier",
  "role",
  "app_user",
  "permission",
  "role_permission",
  "user_role",
  "user_device",
  "setting_definition",
  "setting_value",
  "rule_action_type",
  "rule_set",
  "rule_fact_definition",
  "rule",
  "rule_evaluation_log",
  "workflow",
  "workflow_step",
  "approval_request",
  "approval_action",
  "custom_field_def",
  "doc_template",
  "notification",
  "audit_log",
  "file",
  "student",
  "guardian_link",
  "health",
  "previous_school",
  "enrollment",
  "club",
  "club_membership",
  "incident",
  "exit_request",
  "form_batch",
  "form_sale",
  "application",
  "application_guardian",
  "admission_test",
  "test_score",
  "waitlist",
  "enquiry",
  "visitor",
  "call_log",
  "postal",
  "complaint",
  "gate_pass",
  "term",
  "week",
  "holiday",
  "working_day",
  "event",
  "notice",
];
