import type { EntityConfig } from "./types.js";

export const entities: Record<string, EntityConfig> = {
  campus: {
    key: "campus",
    table: "core.campus",
    title: "Campus",
    titlePlural: "Campuses",
    description: "Physical school locations",
    searchFields: ["code", "name", "short_name"],
    listColumns: ["code", "name", "short_name", "phone", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "short_name", label: "Short name", type: "text" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  school_wing: {
    key: "school_wing",
    table: "core.school_wing",
    title: "School wing",
    titlePlural: "School wings",
    description: "Early Years, Primary, Secondary…",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "sort_order", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  academic_session: {
    key: "academic_session",
    table: "core.academic_session",
    title: "Academic session",
    titlePlural: "Academic sessions",
    description: "School years with date ranges",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "starts_on", "ends_on", "is_current", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true, placeholder: "2026-2027" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "is_current", label: "Current session", type: "boolean", default: false },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "session_status", required: true },
    ],
  },
  class_level: {
    key: "class_level",
    table: "core.class_level",
    title: "Class level",
    titlePlural: "Class levels",
    description: "Master list: Nursery, Grade 1…",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "wing_id", "sort_order", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "name_alt", label: "Alternate name", type: "text" },
      { name: "wing_id", label: "Wing", type: "fk", fkEntity: "school_wing", fkLabel: "name" },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  class_offering: {
    key: "class_offering",
    table: "core.class_offering",
    title: "Class offering",
    titlePlural: "Class offerings",
    description: "A class running in a session at a campus",
    searchFields: [],
    listColumns: ["session_id", "campus_id", "class_level_id", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name", required: true },
      { name: "class_level_id", label: "Class level", type: "fk", fkEntity: "class_level", fkLabel: "name", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  class_section: {
    key: "class_section",
    table: "core.class_section",
    title: "Class section",
    titlePlural: "Class sections",
    searchFields: ["name"],
    listColumns: ["class_offering_id", "name", "capacity", "sort_order", "status_id"],
    fields: [
      { name: "class_offering_id", label: "Class offering", type: "fk", fkEntity: "class_offering", fkLabel: "id", required: true },
      { name: "name", label: "Name", type: "text", required: true, placeholder: "A / Morning / Day" },
      { name: "capacity", label: "Capacity", type: "number", min: 1 },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  subject: {
    key: "subject",
    table: "core.subject",
    title: "Subject",
    titlePlural: "Subjects",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "name_alt", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "name_alt", label: "Alternate name", type: "text" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  class_offering_subject: {
    key: "class_offering_subject",
    table: "core.class_offering_subject",
    title: "Offering subject",
    titlePlural: "Offering subjects",
    searchFields: [],
    listColumns: ["class_offering_id", "subject_id", "is_reportable", "sort_order", "status_id"],
    fields: [
      { name: "class_offering_id", label: "Class offering", type: "fk", fkEntity: "class_offering", fkLabel: "id", required: true },
      { name: "subject_id", label: "Subject", type: "fk", fkEntity: "subject", fkLabel: "name", required: true },
      { name: "is_reportable", label: "On report card", type: "boolean", default: true },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  house: {
    key: "house",
    table: "core.house",
    title: "House",
    titlePlural: "Houses",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "color", "campus_id", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "color", label: "Color", type: "color" },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  department: {
    key: "department",
    table: "core.department",
    title: "Department",
    titlePlural: "Departments",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "department_type_id", "parent_id", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "department_type_id", label: "Type", type: "lookup", lookupType: "department_type" },
      { name: "parent_id", label: "Parent department", type: "fk", fkEntity: "department", fkLabel: "name" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  designation: {
    key: "designation",
    table: "core.designation",
    title: "Designation",
    titlePlural: "Designations",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "rank_order", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "rank_order", label: "Rank order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  geo_unit: {
    key: "geo_unit",
    table: "core.geo_unit",
    title: "Geography unit",
    titlePlural: "Geography",
    searchFields: ["name"],
    listColumns: ["name", "level_id", "parent_id"],
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "level_id", label: "Level", type: "lookup", lookupType: "geo_level", required: true },
      { name: "parent_id", label: "Parent", type: "fk", fkEntity: "geo_unit", fkLabel: "name" },
    ],
  },
  person: {
    key: "person",
    table: "core.person",
    title: "Person",
    titlePlural: "People",
    description: "Shared identity for students, guardians and staff",
    searchFields: ["first_name", "last_name", "name_alt"],
    listColumns: ["first_name", "last_name", "date_of_birth", "gender_id", "status_id"],
    fields: [
      { name: "first_name", label: "First name", type: "text", required: true },
      { name: "last_name", label: "Last name", type: "text" },
      { name: "name_alt", label: "Alternate name", type: "text" },
      { name: "date_of_birth", label: "Date of birth", type: "date" },
      { name: "gender_id", label: "Gender", type: "lookup", lookupType: "gender" },
      { name: "religion_id", label: "Religion", type: "lookup", lookupType: "religion" },
      { name: "nationality_id", label: "Nationality", type: "lookup", lookupType: "nationality" },
      { name: "blood_group_id", label: "Blood group", type: "lookup", lookupType: "blood_group" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  role: {
    key: "role",
    table: "iam.role",
    title: "Role",
    titlePlural: "Roles",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "is_system", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "is_system", label: "System role", type: "boolean", default: false, readonly: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  app_user: {
    key: "app_user",
    table: "iam.app_user",
    title: "App user",
    titlePlural: "Users",
    searchFields: [],
    listColumns: ["person_id", "profile_type_id", "status_id", "last_login_at"],
    fields: [
      { name: "auth_user_id", label: "Auth user ID", type: "text", required: true },
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name", required: true },
      { name: "profile_type_id", label: "Profile type", type: "lookup", lookupType: "profile_type", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "user_status", required: true },
    ],
  },
  permission: {
    key: "permission",
    table: "iam.permission",
    title: "Permission",
    titlePlural: "Permissions",
    searchFields: ["resource"],
    listColumns: ["module_id", "resource", "action_id"],
    fields: [
      { name: "module_id", label: "Module", type: "fk", fkEntity: "module", fkLabel: "name", required: true },
      { name: "resource", label: "Resource", type: "text", required: true },
      { name: "action_id", label: "Action", type: "lookup", lookupType: "permission_action", required: true },
    ],
  },
  role_permission: {
    key: "role_permission",
    table: "iam.role_permission",
    title: "Role permission",
    titlePlural: "Role permissions",
    searchFields: [],
    defaultSort: { field: "role_id", dir: "asc" },
    listColumns: ["role_id", "permission_id"],
    fields: [
      { name: "role_id", label: "Role", type: "fk", fkEntity: "role", fkLabel: "name", required: true },
      { name: "permission_id", label: "Permission", type: "fk", fkEntity: "permission", fkLabel: "resource", required: true },
      { name: "condition", label: "Condition", type: "json" },
    ],
  },
  user_role: {
    key: "user_role",
    table: "iam.user_role",
    title: "User role",
    titlePlural: "User roles",
    searchFields: [],
    listColumns: ["user_id", "role_id", "campus_id", "valid_from", "valid_to"],
    fields: [
      { name: "user_id", label: "User", type: "fk", fkEntity: "app_user", fkLabel: "id", required: true },
      { name: "role_id", label: "Role", type: "fk", fkEntity: "role", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "valid_from", label: "Valid from", type: "date", required: true },
      { name: "valid_to", label: "Valid to", type: "date" },
    ],
  },
  setting_definition: {
    key: "setting_definition",
    table: "shared.setting_definition",
    title: "Setting definition",
    titlePlural: "Setting definitions",
    searchFields: ["key", "name"],
    listColumns: ["module_id", "key", "name", "data_type_id", "is_active"],
    fields: [
      { name: "module_id", label: "Module", type: "fk", fkEntity: "module", fkLabel: "name", required: true },
      { name: "key", label: "Key", type: "text", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "data_type_id", label: "Data type", type: "lookup", lookupType: "data_type", required: true },
      { name: "default_value", label: "Default value (JSON)", type: "json" },
      { name: "is_active", label: "Active", type: "boolean", default: true },
    ],
  },
  setting_value: {
    key: "setting_value",
    table: "shared.setting_value",
    title: "Setting value",
    titlePlural: "Setting values",
    searchFields: [],
    listColumns: ["definition_id", "scope_type_id", "value", "effective_from"],
    fields: [
      { name: "definition_id", label: "Definition", type: "fk", fkEntity: "setting_definition", fkLabel: "name", required: true },
      { name: "scope_type_id", label: "Scope", type: "lookup", lookupType: "scope_type", required: true },
      { name: "scope_id", label: "Scope ID", type: "number" },
      { name: "value", label: "Value (JSON)", type: "json", required: true },
      { name: "effective_from", label: "Effective from", type: "date", required: true },
      { name: "effective_to", label: "Effective to", type: "date" },
    ],
  },
  rule_set: {
    key: "rule_set",
    table: "shared.rule_set",
    title: "Rule set",
    titlePlural: "Rule sets",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "module_id", "subject_type", "eval_mode_id"],
    fields: [
      { name: "module_id", label: "Module", type: "fk", fkEntity: "module", fkLabel: "name", required: true },
      { name: "code", label: "Code", type: "text", required: true, unique: true, placeholder: "payroll.attendance_deduction" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "subject_type", label: "Subject type", type: "text", required: true, placeholder: "employee_month" },
      { name: "eval_mode_id", label: "Eval mode", type: "lookup", lookupType: "rule_eval_mode", required: true },
    ],
  },
  rule: {
    key: "rule",
    table: "shared.rule",
    title: "Rule",
    titlePlural: "Rules",
    searchFields: ["name"],
    listColumns: ["rule_set_id", "name", "priority", "status_id", "version"],
    fields: [
      { name: "rule_set_id", label: "Rule set", type: "fk", fkEntity: "rule_set", fkLabel: "name", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "priority", label: "Priority", type: "number", default: 100, description: "Lower runs first" },
      { name: "scope_type_id", label: "Scope", type: "lookup", lookupType: "scope_type", required: true },
      { name: "condition", label: "Condition (JSON logic)", type: "json", default: {} },
      { name: "actions", label: "Actions (JSON array)", type: "json", required: true, default: [] },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "rule_status", required: true },
      { name: "effective_from", label: "Effective from", type: "date" },
      { name: "effective_to", label: "Effective to", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  workflow: {
    key: "workflow",
    table: "shared.workflow",
    title: "Workflow",
    titlePlural: "Workflows",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "entity_type", "module_id", "status_id"],
    fields: [
      { name: "module_id", label: "Module", type: "fk", fkEntity: "module", fkLabel: "name", required: true },
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "entity_type", label: "Entity type", type: "text", required: true, placeholder: "leave_application" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  workflow_step: {
    key: "workflow_step",
    table: "shared.workflow_step",
    title: "Workflow step",
    titlePlural: "Workflow steps",
    searchFields: ["name"],
    listColumns: ["workflow_id", "step_no", "name", "approver_type_id", "min_approvals"],
    fields: [
      { name: "workflow_id", label: "Workflow", type: "fk", fkEntity: "workflow", fkLabel: "name", required: true },
      { name: "step_no", label: "Step no", type: "number", required: true, min: 1 },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "approver_type_id", label: "Approver type", type: "lookup", lookupType: "approver_type", required: true },
      { name: "approver_ref_id", label: "Approver ref ID", type: "number" },
      { name: "min_approvals", label: "Min approvals", type: "number", default: 1, min: 1 },
      { name: "condition", label: "Condition (JSON)", type: "json" },
    ],
  },
  custom_field_def: {
    key: "custom_field_def",
    table: "shared.custom_field_def",
    title: "Custom field",
    titlePlural: "Custom fields",
    searchFields: ["key", "label"],
    listColumns: ["entity_type_id", "key", "label", "data_type_id", "is_required", "status_id"],
    fields: [
      { name: "entity_type_id", label: "Entity", type: "lookup", lookupType: "custom_entity_type", required: true },
      { name: "key", label: "Key", type: "text", required: true },
      { name: "label", label: "Label", type: "text", required: true },
      { name: "label_alt", label: "Alternate label", type: "text" },
      { name: "data_type_id", label: "Data type", type: "lookup", lookupType: "data_type", required: true },
      { name: "is_required", label: "Required", type: "boolean", default: false },
      { name: "group_label", label: "Group", type: "text" },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  doc_template: {
    key: "doc_template",
    table: "shared.doc_template",
    title: "Document template",
    titlePlural: "Templates",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "template_type_id", "language", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true },
      { name: "version", label: "Version", type: "number", default: 1 },
      { name: "module_id", label: "Module", type: "fk", fkEntity: "module", fkLabel: "name" },
      { name: "template_type_id", label: "Type", type: "lookup", lookupType: "template_type", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "language", label: "Language", type: "text", default: "en" },
      { name: "subject", label: "Subject", type: "text" },
      { name: "body", label: "Body", type: "textarea", required: true, placeholder: "Hello {{person.first_name}}" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  module: {
    key: "module",
    table: "core.module",
    title: "Module",
    titlePlural: "Modules",
    searchFields: ["code", "name"],
    listColumns: ["sort_order", "code", "name", "is_active"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true, readonly: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
      { name: "is_active", label: "Active", type: "boolean", default: true },
    ],
  },
  id_sequence: {
    key: "id_sequence",
    table: "core.id_sequence",
    title: "ID sequence",
    titlePlural: "ID sequences",
    searchFields: ["entity_code", "prefix"],
    listColumns: ["entity_code", "prefix", "padding", "next_number", "session_id"],
    fields: [
      { name: "entity_code", label: "Entity code", type: "text", required: true, placeholder: "student" },
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name" },
      { name: "prefix", label: "Prefix", type: "text", required: true, placeholder: "STD-" },
      { name: "padding", label: "Padding", type: "number", default: 5, min: 1 },
      { name: "next_number", label: "Next number", type: "number", default: 1, min: 1 },
    ],
  },
  student: {
    key: "student",
    table: "student.student",
    title: "Student",
    titlePlural: "Students",
    description: "School roll — one person, yearly facts live on enrolment",
    searchFields: ["student_code"],
    listColumns: ["student_code", "person_id", "campus_id", "admitted_on", "status_id"],
    fields: [
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name", required: true },
      { name: "student_code", label: "Student code", type: "text", required: true, unique: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name", required: true },
      { name: "admitted_on", label: "Admitted on", type: "date" },
      { name: "application_id", label: "Application", type: "fk", fkEntity: "application", fkLabel: "id" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "student_status", required: true },
    ],
  },
  guardian_link: {
    key: "guardian_link",
    table: "student.guardian_link",
    title: "Guardian link",
    titlePlural: "Guardians",
    searchFields: [],
    listColumns: ["student_id", "person_id", "relationship_type_id", "is_primary", "is_emergency"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name", required: true },
      { name: "relationship_type_id", label: "Relationship", type: "lookup", lookupType: "relationship_type", required: true },
      { name: "is_primary", label: "Primary", type: "boolean", default: false },
      { name: "is_emergency", label: "Emergency contact", type: "boolean", default: false },
      { name: "lives_with", label: "Lives with student", type: "boolean", default: false },
    ],
  },
  health: {
    key: "health",
    table: "student.health",
    title: "Health record",
    titlePlural: "Health records",
    searchFields: [],
    listColumns: ["student_id", "allergies", "physician_name"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "allergies", label: "Allergies", type: "textarea" },
      { name: "conditions", label: "Conditions", type: "textarea" },
      { name: "physician_name", label: "Physician", type: "text" },
      { name: "physician_phone", label: "Physician phone", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  previous_school: {
    key: "previous_school",
    table: "student.previous_school",
    title: "Previous school",
    titlePlural: "Previous schools",
    searchFields: ["name"],
    listColumns: ["student_id", "name", "last_class", "years_attended"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "name", label: "School name", type: "text", required: true },
      { name: "last_class", label: "Last class", type: "text" },
      { name: "years_attended", label: "Years attended", type: "text" },
      { name: "leaving_reason", label: "Leaving reason", type: "textarea" },
    ],
  },
  enrollment: {
    key: "enrollment",
    table: "student.enrollment",
    title: "Enrolment",
    titlePlural: "Enrolments",
    description: "Yearly class, section and house",
    searchFields: [],
    listColumns: ["student_id", "session_id", "class_section_id", "house_id", "roll_no", "status_id"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "class_section_id", label: "Class section", type: "fk", fkEntity: "class_section", fkLabel: "name", required: true },
      { name: "house_id", label: "House", type: "fk", fkEntity: "house", fkLabel: "name" },
      { name: "roll_no", label: "Roll no", type: "number", min: 1 },
      { name: "enrolled_on", label: "Enrolled on", type: "date", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "enrollment_status", required: true },
    ],
  },
  club: {
    key: "club",
    table: "student.club",
    title: "Club",
    titlePlural: "Clubs",
    searchFields: ["code", "name"],
    listColumns: ["code", "name", "status_id"],
    fields: [
      { name: "code", label: "Code", type: "text", required: true, unique: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  club_membership: {
    key: "club_membership",
    table: "student.club_membership",
    title: "Club membership",
    titlePlural: "Club memberships",
    searchFields: [],
    listColumns: ["club_id", "student_id", "session_id", "role"],
    fields: [
      { name: "club_id", label: "Club", type: "fk", fkEntity: "club", fkLabel: "name", required: true },
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "role", label: "Role", type: "text" },
    ],
  },
  incident: {
    key: "incident",
    table: "student.incident",
    title: "Incident",
    titlePlural: "Incidents",
    searchFields: ["description"],
    listColumns: ["student_id", "occurred_on", "category_id", "severity_id", "status_id"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "occurred_on", label: "Occurred on", type: "date", required: true },
      { name: "category_id", label: "Category", type: "lookup", lookupType: "incident_category", required: true },
      { name: "severity_id", label: "Severity", type: "lookup", lookupType: "incident_severity", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "action_taken", label: "Action taken", type: "textarea" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  exit_request: {
    key: "exit_request",
    table: "student.exit_request",
    title: "Exit / TC",
    titlePlural: "Exits & TCs",
    searchFields: ["tc_number", "reason"],
    listColumns: ["student_id", "exit_type_id", "requested_on", "tc_number", "status_id"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code", required: true },
      { name: "exit_type_id", label: "Exit type", type: "lookup", lookupType: "exit_type", required: true },
      { name: "requested_on", label: "Requested on", type: "date", required: true },
      { name: "effective_on", label: "Effective on", type: "date" },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "tc_number", label: "TC number", type: "text" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "exit_status", required: true },
    ],
  },
  form_batch: {
    key: "form_batch",
    table: "admission.form_batch",
    title: "Form batch",
    titlePlural: "Form batches",
    searchFields: [],
    listColumns: ["session_id", "campus_id", "class_level_id", "price", "sold_from", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name", required: true },
      { name: "class_level_id", label: "Class level", type: "fk", fkEntity: "class_level", fkLabel: "name", required: true },
      { name: "price", label: "Price", type: "number", min: 0, default: 0 },
      { name: "sold_from", label: "Sold from", type: "date" },
      { name: "sold_to", label: "Sold to", type: "date" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  form_sale: {
    key: "form_sale",
    table: "admission.form_sale",
    title: "Form sale",
    titlePlural: "Form sales",
    searchFields: ["serial_no", "buyer_name", "buyer_phone"],
    listColumns: ["batch_id", "serial_no", "buyer_name", "sold_on", "amount", "status_id"],
    fields: [
      { name: "batch_id", label: "Batch", type: "fk", fkEntity: "form_batch", fkLabel: "id", required: true },
      { name: "serial_no", label: "Serial no", type: "text", required: true },
      { name: "sold_on", label: "Sold on", type: "date", required: true },
      { name: "buyer_name", label: "Buyer name", type: "text", required: true },
      { name: "buyer_phone", label: "Buyer phone", type: "text" },
      { name: "amount", label: "Amount", type: "number", min: 0, default: 0 },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "form_sale_status", required: true },
    ],
  },
  application: {
    key: "application",
    table: "admission.application",
    title: "Application",
    titlePlural: "Applications",
    searchFields: ["notes"],
    listColumns: ["applicant_person_id", "class_level_id", "session_id", "status_id", "submitted_at"],
    fields: [
      { name: "form_sale_id", label: "Form sale", type: "fk", fkEntity: "form_sale", fkLabel: "serial_no" },
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name", required: true },
      { name: "class_level_id", label: "Class level", type: "fk", fkEntity: "class_level", fkLabel: "name", required: true },
      { name: "applicant_person_id", label: "Applicant", type: "fk", fkEntity: "person", fkLabel: "first_name", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "application_status", required: true },
      { name: "submitted_at", label: "Submitted at", type: "datetime" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  application_guardian: {
    key: "application_guardian",
    table: "admission.application_guardian",
    title: "Application guardian",
    titlePlural: "Application guardians",
    searchFields: [],
    listColumns: ["application_id", "person_id", "relationship_type_id"],
    fields: [
      { name: "application_id", label: "Application", type: "fk", fkEntity: "application", fkLabel: "id", required: true },
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name", required: true },
      { name: "relationship_type_id", label: "Relationship", type: "lookup", lookupType: "relationship_type", required: true },
    ],
  },
  admission_test: {
    key: "admission_test",
    table: "admission.test",
    title: "Admission test",
    titlePlural: "Admission tests",
    searchFields: ["name", "venue"],
    listColumns: ["name", "class_level_id", "held_on", "venue", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "class_level_id", label: "Class level", type: "fk", fkEntity: "class_level", fkLabel: "name", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "held_on", label: "Held on", type: "date" },
      { name: "venue", label: "Venue", type: "text" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  test_score: {
    key: "test_score",
    table: "admission.test_score",
    title: "Test score",
    titlePlural: "Test scores",
    searchFields: [],
    listColumns: ["application_id", "test_id", "marks", "remarks"],
    fields: [
      { name: "application_id", label: "Application", type: "fk", fkEntity: "application", fkLabel: "id", required: true },
      { name: "test_id", label: "Test", type: "fk", fkEntity: "admission_test", fkLabel: "name", required: true },
      { name: "marks", label: "Marks", type: "number" },
      { name: "remarks", label: "Remarks", type: "text" },
    ],
  },
  waitlist: {
    key: "waitlist",
    table: "admission.waitlist",
    title: "Waitlist entry",
    titlePlural: "Waitlist",
    searchFields: [],
    listColumns: ["application_id", "position", "added_on"],
    fields: [
      { name: "application_id", label: "Application", type: "fk", fkEntity: "application", fkLabel: "id", required: true },
      { name: "position", label: "Position", type: "number", required: true, min: 1 },
      { name: "added_on", label: "Added on", type: "date", required: true },
    ],
  },
  enquiry: {
    key: "enquiry",
    table: "front.enquiry",
    title: "Enquiry",
    titlePlural: "Enquiries",
    searchFields: ["inquirer_name", "phone", "notes"],
    listColumns: ["inquirer_name", "phone", "class_level_id", "source_id", "follow_up_on", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name" },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "class_level_id", label: "Class level", type: "fk", fkEntity: "class_level", fkLabel: "name" },
      { name: "inquirer_name", label: "Inquirer", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "source_id", label: "Source", type: "lookup", lookupType: "enquiry_source" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "follow_up_on", label: "Follow up on", type: "date" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "enquiry_status", required: true },
    ],
  },
  visitor: {
    key: "visitor",
    table: "front.visitor",
    title: "Visitor",
    titlePlural: "Visitors",
    searchFields: ["name", "badge_no", "visiting"],
    listColumns: ["name", "purpose_id", "visiting", "badge_no", "in_at", "out_at"],
    fields: [
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "purpose_id", label: "Purpose", type: "lookup", lookupType: "visitor_purpose" },
      { name: "visiting", label: "Visiting", type: "text" },
      { name: "badge_no", label: "Badge no", type: "text" },
      { name: "in_at", label: "In at", type: "datetime" },
      { name: "out_at", label: "Out at", type: "datetime" },
    ],
  },
  call_log: {
    key: "call_log",
    table: "front.call_log",
    title: "Call log",
    titlePlural: "Call log",
    searchFields: ["phone", "caller_name", "subject"],
    listColumns: ["direction_id", "caller_name", "phone", "subject", "logged_at"],
    fields: [
      { name: "direction_id", label: "Direction", type: "lookup", lookupType: "call_direction", required: true },
      { name: "phone", label: "Phone", type: "text" },
      { name: "caller_name", label: "Caller", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "logged_at", label: "Logged at", type: "datetime" },
    ],
  },
  postal: {
    key: "postal",
    table: "front.postal",
    title: "Postal item",
    titlePlural: "Postal",
    searchFields: ["ref_no", "from_to", "subject"],
    listColumns: ["direction_id", "ref_no", "from_to", "subject", "received_on", "status_id"],
    fields: [
      { name: "direction_id", label: "Direction", type: "lookup", lookupType: "postal_direction", required: true },
      { name: "ref_no", label: "Ref no", type: "text" },
      { name: "from_to", label: "From / to", type: "text" },
      { name: "subject", label: "Subject", type: "text" },
      { name: "received_on", label: "Date", type: "date", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  complaint: {
    key: "complaint",
    table: "front.complaint",
    title: "Complaint",
    titlePlural: "Complaints",
    searchFields: ["subject", "body"],
    listColumns: ["source_id", "person_id", "subject", "lodged_on", "status_id"],
    fields: [
      { name: "source_id", label: "Source", type: "lookup", lookupType: "complaint_source" },
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name" },
      { name: "subject", label: "Subject", type: "text", required: true },
      { name: "body", label: "Details", type: "textarea" },
      { name: "lodged_on", label: "Lodged on", type: "date", required: true },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "complaint_status", required: true },
    ],
  },
  gate_pass: {
    key: "gate_pass",
    table: "front.gate_pass",
    title: "Gate pass",
    titlePlural: "Gate passes",
    searchFields: ["reason"],
    listColumns: ["student_id", "pass_type_id", "valid_from", "valid_to", "reason", "status_id"],
    fields: [
      { name: "student_id", label: "Student", type: "fk", fkEntity: "student", fkLabel: "student_code" },
      { name: "person_id", label: "Person", type: "fk", fkEntity: "person", fkLabel: "first_name" },
      { name: "pass_type_id", label: "Pass type", type: "lookup", lookupType: "pass_type", required: true },
      { name: "valid_from", label: "Valid from", type: "datetime" },
      { name: "valid_to", label: "Valid to", type: "datetime" },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "pass_status", required: true },
    ],
  },
  term: {
    key: "term",
    table: "cal.term",
    title: "Term",
    titlePlural: "Terms",
    searchFields: ["name"],
    listColumns: ["session_id", "name", "starts_on", "ends_on", "sort_order"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "sort_order", label: "Sort order", type: "number", default: 0 },
    ],
  },
  week: {
    key: "week",
    table: "cal.week",
    title: "Week",
    titlePlural: "Weeks",
    searchFields: [],
    listColumns: ["term_id", "week_no", "starts_on", "ends_on"],
    fields: [
      { name: "term_id", label: "Term", type: "fk", fkEntity: "term", fkLabel: "name", required: true },
      { name: "week_no", label: "Week no", type: "number", required: true, min: 1 },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
    ],
  },
  holiday: {
    key: "holiday",
    table: "cal.holiday",
    title: "Holiday",
    titlePlural: "Holidays",
    searchFields: ["name"],
    listColumns: ["name", "starts_on", "ends_on", "holiday_type_id", "campus_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "name", label: "Name", type: "text", required: true },
      { name: "starts_on", label: "Starts on", type: "date", required: true },
      { name: "ends_on", label: "Ends on", type: "date", required: true },
      { name: "holiday_type_id", label: "Type", type: "lookup", lookupType: "holiday_type", required: true },
    ],
  },
  working_day: {
    key: "working_day",
    table: "cal.working_day",
    title: "Working day",
    titlePlural: "Working-day calendars",
    description: "Weekday pattern per employee group",
    searchFields: [],
    listColumns: ["session_id", "employee_group_id", "weekday", "is_working"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "employee_group_id", label: "Employee group", type: "lookup", lookupType: "employee_group", required: true },
      { name: "weekday", label: "Weekday (0=Sun)", type: "number", required: true, min: 0, max: 6 },
      { name: "is_working", label: "Working", type: "boolean", default: true },
    ],
  },
  event: {
    key: "event",
    table: "cal.event",
    title: "Event",
    titlePlural: "Events",
    searchFields: ["title", "location"],
    listColumns: ["title", "starts_at", "location", "audience_id", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name", required: true },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "starts_at", label: "Starts at", type: "datetime", required: true },
      { name: "ends_at", label: "Ends at", type: "datetime" },
      { name: "location", label: "Location", type: "text" },
      { name: "audience_id", label: "Audience", type: "lookup", lookupType: "event_audience" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
  notice: {
    key: "notice",
    table: "cal.notice",
    title: "Notice",
    titlePlural: "Notices",
    searchFields: ["title", "body"],
    listColumns: ["title", "published_at", "audience_id", "status_id"],
    fields: [
      { name: "session_id", label: "Session", type: "fk", fkEntity: "academic_session", fkLabel: "name" },
      { name: "campus_id", label: "Campus", type: "fk", fkEntity: "campus", fkLabel: "name" },
      { name: "title", label: "Title", type: "text", required: true },
      { name: "body", label: "Body", type: "textarea", required: true },
      { name: "published_at", label: "Published at", type: "datetime" },
      { name: "audience_id", label: "Audience", type: "lookup", lookupType: "notice_audience" },
      { name: "status_id", label: "Status", type: "lookup", lookupType: "record_status", required: true },
    ],
  },
};

export const navGroups = [
  {
    id: "platform",
    label: "Platform setup",
    items: [
      { entity: "campus", path: "/platform/campuses" },
      { entity: "academic_session", path: "/platform/sessions" },
      { entity: "school_wing", path: "/platform/wings" },
      { entity: "class_level", path: "/platform/class-levels" },
      { entity: "class_offering", path: "/platform/offerings" },
      { entity: "class_section", path: "/platform/sections" },
      { entity: "subject", path: "/platform/subjects" },
      { entity: "class_offering_subject", path: "/platform/offering-subjects" },
      { entity: "house", path: "/platform/houses" },
      { entity: "department", path: "/platform/departments" },
      { entity: "designation", path: "/platform/designations" },
      { entity: "geo_unit", path: "/platform/geography" },
      { entity: "person", path: "/platform/people" },
      { entity: "id_sequence", path: "/platform/id-sequences" },
      { entity: "module", path: "/platform/modules" },
    ],
  },
  {
    id: "iam",
    label: "Identity & access",
    items: [
      { entity: "role", path: "/iam/roles" },
      { entity: "app_user", path: "/iam/users" },
      { entity: "permission", path: "/iam/permissions-list" },
      { entity: "role_permission", path: "/iam/role-permissions" },
      { entity: "user_role", path: "/iam/user-roles" },
    ],
  },
  {
    id: "shared",
    label: "Shared services",
    items: [
      { entity: "setting_definition", path: "/shared/setting-defs" },
      { entity: "setting_value", path: "/shared/settings" },
      { entity: "rule_set", path: "/shared/rule-sets" },
      { entity: "rule", path: "/shared/rules" },
      { entity: "workflow", path: "/shared/workflows" },
      { entity: "workflow_step", path: "/shared/workflow-steps" },
      { entity: "custom_field_def", path: "/shared/custom-fields" },
      { entity: "doc_template", path: "/shared/templates" },
    ],
  },
  {
    id: "front",
    label: "Front office",
    items: [
      { entity: "enquiry", path: "/front/enquiries" },
      { entity: "visitor", path: "/front/visitors" },
      { entity: "call_log", path: "/front/calls" },
      { entity: "postal", path: "/front/postal" },
      { entity: "complaint", path: "/front/complaints" },
      { entity: "gate_pass", path: "/front/passes" },
    ],
  },
  {
    id: "admission",
    label: "Admission",
    items: [
      { entity: "form_batch", path: "/admission/batches" },
      { entity: "form_sale", path: "/admission/sales" },
      { entity: "application", path: "/admission/applications" },
      { entity: "application_guardian", path: "/admission/app-guardians" },
      { entity: "admission_test", path: "/admission/tests" },
      { entity: "test_score", path: "/admission/scores" },
      { entity: "waitlist", path: "/admission/waitlist" },
    ],
  },
  {
    id: "student",
    label: "Students",
    items: [
      { entity: "student", path: "/students" },
      { entity: "enrollment", path: "/students/enrolments" },
      { entity: "guardian_link", path: "/students/guardians" },
      { entity: "health", path: "/students/health" },
      { entity: "previous_school", path: "/students/previous-schools" },
      { entity: "club", path: "/students/clubs" },
      { entity: "club_membership", path: "/students/memberships" },
      { entity: "incident", path: "/students/incidents" },
      { entity: "exit_request", path: "/students/exits" },
    ],
  },
  {
    id: "calendar",
    label: "Calendar",
    items: [
      { entity: "term", path: "/calendar/terms" },
      { entity: "week", path: "/calendar/weeks" },
      { entity: "holiday", path: "/calendar/holidays" },
      { entity: "working_day", path: "/calendar/working-days" },
      { entity: "event", path: "/calendar/events" },
      { entity: "notice", path: "/calendar/notices" },
    ],
  },
];
